IMPORT PACKAGE

In [1]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color
from skimage.feature import graycomatrix, graycoprops
from sklearn import svm

IMPORT DATASET

In [2]:
ng_folder = r"D:\Proposal Skripsi gas 2024\skripsi\bahan_penelitian\ng"
ok_folder = r"D:\Proposal Skripsi gas 2024\skripsi\bahan_penelitian\ok"
ng_list = os.listdir(ng_folder)
ok_list = os.listdir(ok_folder)

In [3]:
# ng_first = ng_list[0]
# ok_first = ok_list[0]
# print("File pertama NG:", ng_first)
# print("File pertama OK:", ok_first)

File pertama NG: NG-1-20241007-112615-933.BMP
File pertama OK: OK-1-20241010-112359-043.BMP


ROI NG : (576, 446, 95, 174)

In [16]:
img_path = r"D:\Proposal Skripsi gas 2024\skripsi\bahan_penelitian\ng\NG-1-20241007-112615-933.BMP"
img = cv2.imread(img_path)
x = 576
y = 446
w = 95
h = 174
roi_crop = img[y:y+h, x:x+w]

roi = (x,y,w,h)

cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255), 2)

# cv2.imshow('Image with ROI', img)
cv2.imshow('Image with ROI', roi_crop) ##salah satu antara roi_crop atau img
cv2.waitKey(0)
cv2.destroyAllWindows()
print(roi_crop)

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  4  24   2]
  ...
  [  3  14   2]
  [  3  14   2]
  [  0   0 255]]

 ...

 [[  0   0 255]
  [  0   0 255]
  [  9  31   2]
  ...
  [  3  17   2]
  [  2  17   2]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  6  31   2]
  ...
  [  3  19   2]
  [  2  18   2]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


ROI OK : (590, 456, 100, 170)

In [13]:
img_path = r"D:\Proposal Skripsi gas 2024\skripsi\bahan_penelitian\ok\OK-15-20241010-112506-735.BMP"
img = cv2.imread(img_path)

x = 590
y = 456
w = 100
h = 170
roi_crop = img[y:y+h, x:x+w]

roi = (x,y,w,h)

cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255), 2)

# cv2.imshow('Image with ROI', img)
cv2.imshow('Image with ROI', roi_crop) ##salah satu antara roi_crop atau img
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2
import os

ref_point = []
cropping = False

def select_roi(event, x, y, flags, param):
    global ref_point, cropping

    if event == cv2.EVENT_LBUTTONDOWN:
        ref_point = [(x, y)]
        cropping = True

    elif event == cv2.EVENT_LBUTTONUP:
        ref_point.append((x, y))
        cropping = False
        cv2.rectangle(image, ref_point[0], ref_point[1], (0, 255, 0), 2)
        cv2.imshow("image", image)

image_path = r"D:\Proposal Skripsi gas 2024\skripsi\bahan_penelitian\ng\NG-1-20241007-112615-933.BMP"

if not os.path.exists(image_path):
    print(f"File tidak ditemukan di lokasi: {image_path}")
    exit()

image = cv2.imread(image_path)
if image is None:
    print("Gambar tidak ditemukan. Periksa kembali path gambar atau format file.")
    exit()

clone = image.copy()

cv2.namedWindow("image")
cv2.setMouseCallback("image", select_roi)

while True:
    # Tampilkan gambar
    cv2.imshow("image", image)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("r"):
        image = clone.copy()

    elif key == ord("c"):
        break

if len(ref_point) == 2:
    x1, y1 = ref_point[0]
    x2, y2 = ref_point[1]

    if 0 <= x1 < x2 <= clone.shape[1] and 0 <= y1 < y2 <= clone.shape[0]:
        roi = clone[y1:y2, x1:x2]
        cv2.imshow("Cropped Image", roi)
        cv2.imwrite("cropped_image.jpg", roi)
        cv2.waitKey(0)
    else:
        print("Koordinat cropping berada di luar batas gambar.")
cv2.destroyAllWindows()

if len(ref_point) == 2:
    print(f"Koordinat awal (x1, y1): {ref_point[0]}")
    print(f"Koordinat akhir (x2, y2): {ref_point[1]}")

    width = x2 - x1
    height = y2 - y1
    print(f"Lebar ROI: {width}")
    print(f"Tinggi ROI: {height}")


Koordinat awal (x1, y1): (574, 445)
Koordinat akhir (x2, y2): (689, 637)
Lebar ROI: 115
Tinggi ROI: 192
